name: esptouchflutter
description: ESP Touch Test
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.8+6
  cupertino_icons: ^0.1.2
  esptouch_flutter: ^0.2.4
  passwordfield: ^0.0.6
  permission_handler: ^5.0.1
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/other/
